# -*- coding: utf-8 -*-
"""lab06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOkOGZWE9YgGDK9K5aJfDm96JbTa59kh
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist, fashion_mnist, cifar10
import matplotlib.pyplot as plt

# Veri kümelerini yükle
(x_train_mnist, y_train_mnist), (x_test_mnist, y_test_mnist) = mnist.load_data()
(x_train_fmnist, y_train_fmnist), (x_test_fmnist, y_test_fmnist) = fashion_mnist.load_data()
(x_train_cifar, y_train_cifar), (x_test_cifar, y_test_cifar) = cifar10.load_data()

# Shape karşılaştırması
print("=== SHAPE KARŞILAŞTIRMASI ===")
print(f"MNIST       - Eğitim: {x_train_mnist.shape}, Test: {x_test_mnist.shape}")
print(f"Fashion-MNIST - Eğitim: {x_train_fmnist.shape}, Test: {x_test_fmnist.shape}")
print(f"CIFAR-10    - Eğitim: {x_train_cifar.shape}, Test: {x_test_cifar.shape}")

# Normalizasyon
x_train_mnist = x_train_mnist / 255.0
x_train_fmnist = x_train_fmnist / 255.0
x_train_cifar = x_train_cifar / 255.0

print("\nNormalizasyon tamamlandı. Tüm piksel değerleri [0,1] aralığında.")

# Örnek görseller
fig, axes = plt.subplots(1, 3, figsize=(10,4))
axes[0].imshow(x_train_mnist[0], cmap='gray'); axes[0].set_title("MNIST")
axes[1].imshow(x_train_fmnist[0], cmap='gray'); axes[1].set_title("Fashion-MNIST")
axes[2].imshow(x_train_cifar[0]); axes[2].set_title("CIFAR-10")
plt.show()

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, InputLayer

# --- Satır 1: 28x28x1, 3x3, Stride=1, Valid ---
model1 = Sequential([
    InputLayer(input_shape=(28, 28, 1)),
    Conv2D(1, (3,3), strides=1, padding='valid')
])
print("Satır 1 (valid):")
model1.summary()

# --- Satır 2: 28x28x1, 3x3, Stride=1, Same ---
model2 = Sequential([
    InputLayer(input_shape=(28, 28, 1)),
    Conv2D(1, (3,3), strides=1, padding='same')
])
print("Satır 2 (same):")
model2.summary()

# --- Satır 3: 32x32x3, 5x5, Stride=2, Valid ---
model3 = Sequential([
    InputLayer(input_shape=(32, 32, 3)),
    Conv2D(1, (5,5), strides=2, padding='valid')
])
print("Satır 3 (valid, stride=2):")
model3.summary()

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.datasets import fashion_mnist
import time

# Veriyi hazırla
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train = x_train.reshape(-1, 28, 28, 1) / 255.0
x_test = x_test.reshape(-1, 28, 28, 1) / 255.0

# --- MODEL 1: MaxPooling kullanan model ---
model_pool = Sequential([
    Conv2D(32, (3,3), activation='relu', padding='same', input_shape=(28,28,1)),
    MaxPooling2D(pool_size=(2,2)),
    Conv2D(64, (3,3), activation='relu', padding='same'),
    MaxPooling2D(pool_size=(2,2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
], name="MaxPooling_Model")

# --- MODEL 2: Stride=2 kullanan model ---
model_stride = Sequential([
    Conv2D(32, (3,3), activation='relu', padding='same', strides=2, input_shape=(28,28,1)),
    Conv2D(64, (3,3), activation='relu', padding='same', strides=2),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
], name="Stride2_Model")

# Her iki modeli derle
model_pool.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model_stride.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Özetleri yazdır
print("=== MODEL 1: MaxPooling ===")
model_pool.summary()

print("\n=== MODEL 2: Stride=2 ===")
model_stride.summary()

# Eğit
print("\nModel 1 eğitiliyor...")
h1 = model_pool.fit(x_train, y_train, epochs=5, batch_size=64,
                     validation_data=(x_test, y_test), verbose=1)

print("\nModel 2 eğitiliyor...")
h2 = model_stride.fit(x_train, y_train, epochs=5, batch_size=64,
                       validation_data=(x_test, y_test), verbose=1)

# Sonuçları karşılaştır
pool_acc = max(h1.history['val_accuracy'])
stride_acc = max(h2.history['val_accuracy'])

print("\n========== SONUÇLAR ==========")
print(f"MaxPooling Modeli  - En iyi val_accuracy: {pool_acc:.4f}")
print(f"Stride=2 Modeli    - En iyi val_accuracy: {stride_acc:.4f}")

import matplotlib.pyplot as plt

epochs = range(1, 6)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# --- ACCURACY GRAFİĞİ ---
axes[0].plot(epochs, h1.history['accuracy'], 'b-o', label='MaxPooling - Train')
axes[0].plot(epochs, h1.history['val_accuracy'], 'b--o', label='MaxPooling - Val')
axes[0].plot(epochs, h2.history['accuracy'], 'r-o', label='Stride=2 - Train')
axes[0].plot(epochs, h2.history['val_accuracy'], 'r--o', label='Stride=2 - Val')
axes[0].set_title('Model Accuracy Karşılaştırması')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Accuracy')
axes[0].legend()
axes[0].grid(True)

# --- LOSS GRAFİĞİ ---
axes[1].plot(epochs, h1.history['loss'], 'b-o', label='MaxPooling - Train')
axes[1].plot(epochs, h1.history['val_loss'], 'b--o', label='MaxPooling - Val')
axes[1].plot(epochs, h2.history['loss'], 'r-o', label='Stride=2 - Train')
axes[1].plot(epochs, h2.history['val_loss'], 'r--o', label='Stride=2 - Val')
axes[1].set_title('Model Loss Karşılaştırması')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss')
axes[1].legend()
axes[1].grid(True)

plt.tight_layout()
plt.savefig('model_karsilastirma.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\nMaxPooling  - Train Acc: {max(h1.history['accuracy']):.4f} | Val Acc: {max(h1.history['val_accuracy']):.4f}")
print(f"Stride=2    - Train Acc: {max(h2.history['accuracy']):.4f} | Val Acc: {max(h2.history['val_accuracy']):.4f}")

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

# === DEĞERLER ===
epochs = [1, 2, 3, 4, 5]

mp_train_acc  = [0.8440, 0.8979, 0.9122, 0.9243, 0.9342]
mp_val_acc    = [0.8787, 0.8935, 0.9064, 0.9127, 0.9125]
mp_train_loss = [0.4321, 0.2831, 0.2372, 0.2062, 0.1787]
mp_val_loss   = [0.3411, 0.2977, 0.2571, 0.2446, 0.2406]

st_train_acc  = [0.8363, 0.8890, 0.9056, 0.9166, 0.9269]
st_val_acc    = [0.8650, 0.8872, 0.8981, 0.9048, 0.8974]
st_train_loss = [0.4561, 0.3049, 0.2568, 0.2236, 0.1949]
st_val_loss   = [0.3644, 0.3034, 0.2805, 0.2604, 0.2838]

# === RENK PALETİ ===
blue       = '#378ADD'
blue_light = '#B5D4F4'
coral      = '#D85A30'
coral_light= '#F5C4B3'

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.patch.set_facecolor('#FAFAFA')

for ax in axes:
    ax.set_facecolor('#F7F7F7')
    ax.grid(True, color='white', linewidth=1.5, linestyle='-')
    ax.set_xticks(epochs)
    ax.set_xticklabels([f'Epoch {e}' for e in epochs], fontsize=10)
    ax.tick_params(axis='y', labelsize=10)
    for spine in ax.spines.values():
        spine.set_visible(False)

# === ACCURACY GRAFİĞİ ===
ax = axes[0]
ax.plot(epochs, mp_train_acc, color=blue,        marker='o', linewidth=2.5, markersize=7, label='MaxPooling - Train')
ax.plot(epochs, mp_val_acc,   color=blue,        marker='s', linewidth=2.5, markersize=7, linestyle='--', label='MaxPooling - Val')
ax.plot(epochs, st_train_acc, color=coral,       marker='o', linewidth=2.5, markersize=7, label='Stride=2 - Train')
ax.plot(epochs, st_val_acc,   color=coral,       marker='s', linewidth=2.5, markersize=7, linestyle='--', label='Stride=2 - Val')

ax.fill_between(epochs, mp_train_acc, mp_val_acc, alpha=0.08, color=blue)
ax.fill_between(epochs, st_train_acc, st_val_acc, alpha=0.08, color=coral)

ax.set_title('Accuracy Karşılaştırması', fontsize=13, fontweight='bold', pad=12)
ax.set_ylabel('Accuracy', fontsize=11)
ax.set_ylim(0.80, 0.96)
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f'{v*100:.1f}%'))

for x, y in zip(epochs, mp_val_acc):
    ax.annotate(f'{y:.4f}', (x, y), textcoords="offset points", xytext=(0, 10),
                ha='center', fontsize=8, color=blue)
for x, y in zip(epochs, st_val_acc):
    ax.annotate(f'{y:.4f}', (x, y), textcoords="offset points", xytext=(0, -16),
                ha='center', fontsize=8, color=coral)

# === LOSS GRAFİĞİ ===
ax = axes[1]
ax.plot(epochs, mp_train_loss, color=blue,  marker='o', linewidth=2.5, markersize=7)
ax.plot(epochs, mp_val_loss,   color=blue,  marker='s', linewidth=2.5, markersize=7, linestyle='--')
ax.plot(epochs, st_train_loss, color=coral, marker='o', linewidth=2.5, markersize=7)
ax.plot(epochs, st_val_loss,   color=coral, marker='s', linewidth=2.5, markersize=7, linestyle='--')

ax.fill_between(epochs, mp_train_loss, mp_val_loss, alpha=0.08, color=blue)
ax.fill_between(epochs, st_train_loss, st_val_loss, alpha=0.08, color=coral)

ax.set_title('Loss Karşılaştırması', fontsize=13, fontweight='bold', pad=12)
ax.set_ylabel('Loss', fontsize=11)

for x, y in zip(epochs, mp_val_loss):
    ax.annotate(f'{y:.4f}', (x, y), textcoords="offset points", xytext=(0, 10),
                ha='center', fontsize=8, color=blue)
for x, y in zip(epochs, st_val_loss):
    ax.annotate(f'{y:.4f}', (x, y), textcoords="offset points", xytext=(0, -16),
                ha='center', fontsize=8, color=coral)

# === ORTAK LEGEND ===
legend_elements = [
    mpatches.Patch(color=blue,        label='MaxPooling - Train'),
    mpatches.Patch(color=blue_light,  label='MaxPooling - Val',   linestyle='--'),
    mpatches.Patch(color=coral,       label='Stride=2 - Train'),
    mpatches.Patch(color=coral_light, label='Stride=2 - Val'),
]
fig.legend(handles=legend_elements, loc='lower center', ncol=4,
           fontsize=10, frameon=False, bbox_to_anchor=(0.5, -0.04))

plt.suptitle('MaxPooling vs Stride=2 — Model Karşılaştırması',
             fontsize=14, fontweight='bold', y=1.02)

plt.tight_layout()
plt.savefig('model_karsilastirma.png', dpi=150, bbox_inches='tight',
            facecolor=fig.get_facecolor())
plt.show()
print("Grafik 'model_karsilastirma.png' olarak kaydedildi.")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.datasets import fashion_mnist
from sklearn.metrics import confusion_matrix

# === VERİ HAZIRLA ===
class_names = ['T-shirt','Trouser','Pullover','Dress','Coat',
                'Sandal','Shirt','Sneaker','Bag','Ankle boot']

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
x_train = x_train.reshape(-1, 28, 28, 1) / 255.0
x_test  = x_test.reshape(-1, 28, 28, 1) / 255.0

# === MODELİ KUR ===
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    MaxPooling2D(2,2),
    Conv2D(64, (3,3), activation='relu'),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

# === EĞİT ===
history = model.fit(x_train, y_train, epochs=10, batch_size=64,
                    validation_data=(x_test, y_test), verbose=1)

# === 1. GRAFİK: Accuracy & Loss ===
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.patch.set_facecolor('#FAFAFA')
epochs_range = range(1, 11)

for ax in axes:
    ax.set_facecolor('#F7F7F7')
    ax.grid(True, color='white', linewidth=1.5)
    for spine in ax.spines.values():
        spine.set_visible(False)

axes[0].plot(epochs_range, history.history['accuracy'],     color='#378ADD', marker='o', linewidth=2.5, label='Train')
axes[0].plot(epochs_range, history.history['val_accuracy'], color='#378ADD', marker='s', linewidth=2.5, linestyle='--', label='Validation')
axes[0].fill_between(epochs_range, history.history['accuracy'], history.history['val_accuracy'], alpha=0.08, color='#378ADD')
axes[0].set_title('Model Accuracy', fontsize=13, fontweight='bold')
axes[0].set_ylabel('Accuracy'); axes[0].set_xlabel('Epoch')
axes[0].yaxis.set_major_formatter(plt.FuncFormatter(lambda v,_: f'{v*100:.1f}%'))
axes[0].legend()

axes[1].plot(epochs_range, history.history['loss'],     color='#D85A30', marker='o', linewidth=2.5, label='Train')
axes[1].plot(epochs_range, history.history['val_loss'], color='#D85A30', marker='s', linewidth=2.5, linestyle='--', label='Validation')
axes[1].fill_between(epochs_range, history.history['loss'], history.history['val_loss'], alpha=0.08, color='#D85A30')
axes[1].set_title('Model Loss', fontsize=13, fontweight='bold')
axes[1].set_ylabel('Loss'); axes[1].set_xlabel('Epoch')
axes[1].legend()

plt.suptitle('Fashion-MNIST CNN — Eğitim Süreci', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('uygulama4_accuracy_loss.png', dpi=150, bbox_inches='tight')
plt.show()

# === 2. GRAFİK: Confusion Matrix ===
y_pred = np.argmax(model.predict(x_test), axis=1)
cm = confusion_matrix(y_test, y_pred)

fig, ax = plt.subplots(figsize=(12, 10))
fig.patch.set_facecolor('#FAFAFA')
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names,
            linewidths=0.5, linecolor='white', ax=ax,
            cbar_kws={'shrink': 0.8})
ax.set_xlabel('Tahmin Edilen', fontsize=12, fontweight='bold', labelpad=10)
ax.set_ylabel('Gerçek', fontsize=12, fontweight='bold', labelpad=10)
ax.set_title('Confusion Matrix — Fashion-MNIST', fontsize=14, fontweight='bold', pad=15)
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(rotation=0, fontsize=10)
plt.tight_layout()
plt.savefig('uygulama4_confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

# === 3. GRAFİK: En çok karıştırılan 3 sınıf ===
np.fill_diagonal(cm, 0)
errors = []
for i in range(10):
    for j in range(10):
        if i != j and cm[i,j] > 0:
            errors.append((cm[i,j], class_names[i], class_names[j]))
errors.sort(reverse=True)
top3 = errors[:3]

fig, ax = plt.subplots(figsize=(8, 5))
fig.patch.set_facecolor('#FAFAFA')
ax.set_facecolor('#F7F7F7')
for spine in ax.spines.values():
    spine.set_visible(False)

labels = [f'{e[1]}\n→ {e[2]}' for e in top3]
values = [e[0] for e in top3]
colors = ['#378ADD', '#D85A30', '#1D9E75']
bars = ax.barh(labels, values, color=colors, height=0.5, edgecolor='white')

for bar, val in zip(bars, values):
    ax.text(bar.get_width() + 5, bar.get_y() + bar.get_height()/2,
            str(val), va='center', fontsize=12, fontweight='bold')

ax.set_xlabel('Yanlış Tahmin Sayısı', fontsize=11)
ax.set_title('En Çok Karıştırılan 3 Sınıf Çifti', fontsize=13, fontweight='bold', pad=12)
ax.grid(True, axis='x', color='white', linewidth=1.5)
plt.tight_layout()
plt.savefig('uygulama4_top3_errors.png', dpi=150, bbox_inches='tight')
plt.show()

# === ÖZET ===
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
print(f"\n{'='*40}")
print(f"Test Accuracy : {test_acc*100:.2f}%")
print(f"Test Loss     : {test_loss:.4f}")
print(f"\nEn çok karıştırılan 3 sınıf:")
for i, (count, true_cls, pred_cls) in enumerate(top3, 1):
    print(f"  {i}. {true_cls:12s} → {pred_cls:12s} ({count} hata)")